apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docvault-web
  namespace: docvault
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.docvault.id.vn
      secretName: docvault-app-tls
  rules:
    - host: app.docvault.id.vn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docvault-web
                port:
                  number: 3006
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docvault-keycloak
  namespace: docvault
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - auth.docvault.id.vn
      secretName: docvault-auth-tls
  rules:
    - host: auth.docvault.id.vn
      http:
        paths:
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: /realms
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: /resources
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
