# audit-service values
namespace: docvault

image:
  repository: "harbor.docvault.id.vn/docvault-dev/audit-service"
  tag: "v6-ba3f0fe16256"
  digest: "sha256:87d99ba5acb5701e8be15c8c21354050000d8cab89111ebec0856e5d9b785f2a"

healthPath: /health

service:
  type: ClusterIP
  port: 3004
env:
  NODE_ENV: production
  PORT: "3004"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_ISSUER: "https://auth.docvault.id.vn/realms/docvault"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"

envFrom:
  - secretRef:
      name: docvault-app-secrets
