# metadata-service values
namespace: docvault

image:
  repository: "harbor.docvault.id.vn/docvault-dev/metadata-service"
  tag: "6b6db2e2f46c"
  digest: "sha256:c1fbd1833a4742b12e48699e5b9e340d020c74d6b28da936df4696612f603439"

healthPath: /health

service:
  type: ClusterIP
  port: 3001
env:
  NODE_ENV: production
  PORT: "3001"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_ISSUER: "https://auth.docvault.id.vn/realms/docvault"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"

envFrom:
  - secretRef:
      name: docvault-app-secrets

migration:
  enabled: true
  command: "./node_modules/.bin/prisma migrate deploy"
  backoffLimit: 3
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

seed:
  enabled: false
  nameSuffix: seed
  command: "pnpm db:seed"
  backoffLimit: 1
  ttlSecondsAfterFinished: null
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
