# metadata-service values
namespace: docvault

image:
  repository: "harbor.docvault.id.vn/docvault-dev/metadata-service"
  tag: "v6-ba3f0fe16256"
  digest: "sha256:320498876beb824b77e8d155929473fd4ec057bc1feaf09764dfa8150034e942"

healthPath: /health

service:
  type: ClusterIP
  port: 3001
env:
  NODE_ENV: production
  PORT: "3001"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_ISSUER: "https://auth.docvault.id.vn/realms/docvault"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"

envFrom:
  - secretRef:
      name: docvault-app-secrets

migration:
  enabled: true
  command: "./node_modules/.bin/prisma migrate deploy"
  backoffLimit: 3
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
