# notification-service values
image:
  repository: duyimew/notification-service
  tag: "v81"

service:
  port: 3005

env:
  NODE_ENV: production
  PORT: "3005"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"

envFrom:
  - secretRef:
      name: docvault-app-secrets
