# notification-service values
namespace: default

image:
  repository: daithang59/notification-service
  tag: "v23"
  digest: "sha256:9307116d50d8de198d66d9e7f254d6d6f11b66d81502daa8c7cab88dd1298596"

healthPath: /health

service:
  type: NodePort
  port: 3005
  nodePort: 30005
env:
  NODE_ENV: production
  PORT: "3005"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"

envFrom:
  - secretRef:
      name: docvault-app-secrets
