# web app values
namespace: default

image:
  repository: daithang59/docvault
  tag: "v23"
  digest: "sha256:6250b18e066094b232c6d468ebfd7ab28dbdddb4d79e8e04e599bdcb31ec6b0b"

healthPath: /api/health

service:
  type: NodePort
  port: 3006
  nodePort: 30006
env:
  NODE_ENV: production
  PORT: "3006"
  NEXT_PUBLIC_APP_NAME: "DocVault"
  NEXT_PUBLIC_API_BASE_URL: "http://10.0.3.138:30000/api"
  GATEWAY_URL: "http://10.0.3.138:30000"
  FRONTEND_URL: "http://10.0.3.138:30006"
