# web app values
namespace: docvault

image:
  repository: "harbor.docvault.id.vn/docvault-dev/docvault"
  tag: "v8-2019b9dcef2e"
  digest: "sha256:eaee67d14cb348e5ca3089ad14d24b75351dce36d2e7944db17cf3b3ad8e4672"

healthPath: /api/health

service:
  type: ClusterIP
  port: 3006
env:
  NODE_ENV: production
  PORT: "3006"
  NEXT_PUBLIC_APP_NAME: "DocVault"
  NEXT_PUBLIC_API_BASE_URL: "/api"
  GATEWAY_URL: "http://docvault-gateway:3000"
  KEYCLOAK_INTERNAL_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_CLIENT_ID: "docvault-gateway"
  FRONTEND_URL: "https://app.docvault.id.vn"
  KEYCLOAK_BROWSER_BASE_URL: "https://auth.docvault.id.vn"

envFrom:
  - secretRef:
      name: docvault-app-secrets
