# web app values
namespace: docvault

image:
  repository: "harbor.docvault.id.vn/docvault-dev/docvault"
  tag: "6b6db2e2f46c"
  digest: "sha256:073ac4ec90af20eb8b6fac5f3891d09e50f4fdef31dd68e1f61fd4feace17f9e"

healthPath: /api/health

service:
  type: ClusterIP
  port: 3006
env:
  NODE_ENV: production
  PORT: "3006"
  NEXT_PUBLIC_APP_NAME: "DocVault"
  NEXT_PUBLIC_API_BASE_URL: "/api"
  GATEWAY_URL: "http://docvault-gateway:3000"
  KEYCLOAK_INTERNAL_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_CLIENT_ID: "docvault-gateway"
  FRONTEND_URL: "https://app.docvault.id.vn"
  KEYCLOAK_BROWSER_BASE_URL: "https://auth.docvault.id.vn"

envFrom:
  - secretRef:
      name: docvault-app-secrets
