# workflow-service values
namespace: docvault

image:
  repository: "harbor.docvault.id.vn/docvault-dev/workflow-service"
  tag: "v8-2019b9dcef2e"
  digest: "sha256:b00bf3bf4b9c02744d4f7b23e902f2c1f5d9793c56e7c44dff01bca58a08152e"

healthPath: /health

service:
  type: ClusterIP
  port: 3003
env:
  NODE_ENV: production
  PORT: "3003"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_ISSUER: "https://auth.docvault.id.vn/realms/docvault"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  METADATA_SERVICE_URL: "http://docvault-metadata:3001"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"
  NOTIFICATION_SERVICE_URL: "http://docvault-notification-service:3005"

envFrom:
  - secretRef:
      name: docvault-app-secrets
