# workflow-service values
namespace: docvault

image:
  repository: "harbor.docvault.id.vn/docvault-dev/workflow-service"
  tag: "v6-ba3f0fe16256"
  digest: "sha256:ed5571fa751d1b3cf7bfa942acfefd99dab71a09c605e0d047e11f622fc97c97"

healthPath: /health

service:
  type: ClusterIP
  port: 3003
env:
  NODE_ENV: production
  PORT: "3003"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_ISSUER: "https://auth.docvault.id.vn/realms/docvault"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  METADATA_SERVICE_URL: "http://docvault-metadata:3001"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"
  NOTIFICATION_SERVICE_URL: "http://docvault-notification-service:3005"

envFrom:
  - secretRef:
      name: docvault-app-secrets
