# workflow-service values
namespace: default

image:
  repository: daithang59/workflow-service
  tag: "v23"
  digest: "sha256:4d66c033092322dc4e3b5c9bf2c51755935a60008e8e7214489299073ff77556"

healthPath: /health

service:
  type: NodePort
  port: 3003
  nodePort: 30003
env:
  NODE_ENV: production
  PORT: "3003"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "docvault"
  KEYCLOAK_AUDIENCE: "docvault-gateway"
  METADATA_SERVICE_URL: "http://docvault-metadata:3001"
  AUDIT_SERVICE_URL: "http://docvault-audit-service:3004"
  NOTIFICATION_SERVICE_URL: "http://docvault-notification-service:3005"

envFrom:
  - secretRef:
      name: docvault-app-secrets
