apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/common-harbor.yaml
        - ../../values/gateway.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/env
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-metadata
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/common-harbor.yaml
        - ../../values/metadata-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-audit-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/common-harbor.yaml
        - ../../values/audit-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-notification-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/common-harbor.yaml
        - ../../values/notification-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/env
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-workflow-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/common-harbor.yaml
        - ../../values/workflow-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/env
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-document-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/common-harbor.yaml
        - ../../values/document-service.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/env
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-web
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: gitops-testing
    path: infra/k8s/charts/docvault-service
    helm:
      valueFiles:
        - ../../values/common-harbor.yaml
        - ../../values/web.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/env
