apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docvault-public-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/daithang59/docvault.git'
    targetRevision: main
    path: infra/k8s/public-ingress/overlays/testing
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: docvault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
