apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audit-mongodb-app-credentials
  namespace: docvault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: audit-mongodb-app-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: /docvault/testing/audit-mongodb
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
